import { JobApplication } from 'src/applications/application.model';

export const applications: JobApplication[] = [
  {
    id: '1',
    jobTitle: 'Frontend Developer',
    companyName: 'TechCorp',
    status: 'accepted',
    dateApplied: '2024-01-15',
  },
  {
    id: '2',
    jobTitle: 'Backend Developer',
    companyName: 'WebSolutions',
    status: 'pending',
    dateApplied: '2024-02-17',
  },
  {
    id: '3',
    jobTitle: 'Product Manager',
    companyName: 'InnoTech',
    status: 'rejected',
    dateApplied: '2024-03-09',
  },
  {
    id: '4',
    jobTitle: 'UX Designer',
    companyName: 'InnovateX',
    status: 'accepted',
    dateApplied: '2024-04-22',
  },
  {
    id: '5',
    jobTitle: 'Data Scientist',
    companyName: 'DataForge',
    status: 'pending',
    dateApplied: '2024-05-05',
  },
  {
    id: '6',
    jobTitle: 'Frontend Developer',
    companyName: 'TechCorp',
    status: 'rejected',
    dateApplied: '2024-06-12',
  },
  {
    id: '7',
    jobTitle: 'Backend Developer',
    companyName: 'WebSolutions',
    status: 'accepted',
    dateApplied: '2024-07-03',
  },
  {
    id: '8',
    jobTitle: 'Product Manager',
    companyName: 'InnoTech',
    status: 'pending',
    dateApplied: '2024-08-18',
  },
  {
    id: '9',
    jobTitle: 'UX Designer',
    companyName: 'InnovateX',
    status: 'rejected',
    dateApplied: '2024-09-06',
  },
  {
    id: '10',
    jobTitle: 'Data Scientist',
    companyName: 'DataForge',
    status: 'accepted',
    dateApplied: '2024-10-15',
  },
  {
    id: '11',
    jobTitle: 'Frontend Developer',
    companyName: 'TechCorp',
    status: 'pending',
    dateApplied: '2024-11-01',
  },
  {
    id: '12',
    jobTitle: 'Backend Developer',
    companyName: 'WebSolutions',
    status: 'rejected',
    dateApplied: '2024-12-10',
  },
  {
    id: '13',
    jobTitle: 'Product Manager',
    companyName: 'InnoTech',
    status: 'accepted',
    dateApplied: '2024-01-25',
  },
  {
    id: '14',
    jobTitle: 'UX Designer',
    companyName: 'InnovateX',
    status: 'pending',
    dateApplied: '2024-02-08',
  },
  {
    id: '15',
    jobTitle: 'Data Scientist',
    companyName: 'DataForge',
    status: 'rejected',
    dateApplied: '2024-03-18',
  },
  {
    id: '16',
    jobTitle: 'Frontend Developer',
    companyName: 'TechCorp',
    status: 'accepted',
    dateApplied: '2024-04-04',
  },
  {
    id: '17',
    jobTitle: 'Backend Developer',
    companyName: 'WebSolutions',
    status: 'pending',
    dateApplied: '2024-05-19',
  },
  {
    id: '18',
    jobTitle: 'Product Manager',
    companyName: 'InnoTech',
    status: 'rejected',
    dateApplied: '2024-06-27',
  },
  {
    id: '19',
    jobTitle: 'UX Designer',
    companyName: 'InnovateX',
    status: 'accepted',
    dateApplied: '2024-07-09',
  },
  {
    id: '20',
    jobTitle: 'Data Scientist',
    companyName: 'DataForge',
    status: 'pending',
    dateApplied: '2024-08-02',
  },
  {
    id: '21',
    jobTitle: 'Frontend Developer',
    companyName: 'TechCorp',
    status: 'rejected',
    dateApplied: '2024-09-15',
  },
  {
    id: '22',
    jobTitle: 'Backend Developer',
    companyName: 'WebSolutions',
    status: 'accepted',
    dateApplied: '2024-10-20',
  },
  {
    id: '23',
    jobTitle: 'Product Manager',
    companyName: 'InnoTech',
    status: 'pending',
    dateApplied: '2024-11-30',
  },
  {
    id: '24',
    jobTitle: 'UX Designer',
    companyName: 'InnovateX',
    status: 'rejected',
    dateApplied: '2024-12-06',
  },
  {
    id: '25',
    jobTitle: 'Data Scientist',
    companyName: 'DataForge',
    status: 'accepted',
    dateApplied: '2024-01-08',
  },
  {
    id: '26',
    jobTitle: 'Frontend Developer',
    companyName: 'TechCorp',
    status: 'pending',
    dateApplied: '2024-02-20',
  },
  {
    id: '27',
    jobTitle: 'Backend Developer',
    companyName: 'WebSolutions',
    status: 'rejected',
    dateApplied: '2024-03-14',
  },
  {
    id: '28',
    jobTitle: 'Product Manager',
    companyName: 'InnoTech',
    status: 'accepted',
    dateApplied: '2024-04-25',
  },
  {
    id: '29',
    jobTitle: 'UX Designer',
    companyName: 'InnovateX',
    status: 'pending',
    dateApplied: '2024-05-30',
  },
  {
    id: '30',
    jobTitle: 'Data Scientist',
    companyName: 'DataForge',
    status: 'rejected',
    dateApplied: '2024-06-15',
  },
];
